DROP TABLE IF EXISTS feschtla;
DROP TABLE IF EXISTS pics;

CREATE TABLE feschtla (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL
);

CREATE TABLE pics (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    fescht_id INTEGER NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    filename TEXT NOT NULL,
    thumbname TEXT NOT NULL
);